Repository woowacourse-teams/2021-see-you-there, pull requests merged in 2021-10, with the labels that each got.

#248 [1] board adoc 수정
  backend/goodday/src/docs/asciidoc/board.adoc
  backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
Labels: 😎 BE, ⚒ 리팩토링

#249 [1] BoardLabel to type 으로 변경
  backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dao/BoardRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/Board.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/BoardType.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/BoardRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/BoardResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java
  backend/goodday/src/main/resources/db/migration/V3__altertable.sql
  backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/board/domain/BoardTest.java
Labels: 😎 BE, ⚒ 리팩토링

#251 [1] JPA 쿼리 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/AdminRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/RequestFriendRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 😎 BE, ⚒ 리팩토링

#253 [5] 민감정보 마스킹 기능 추가
  backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/AbstractCryptoConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/ConverterException.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoDoubleConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoStringConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
  backend/goodday/src/main/resources/db/migration/V4__cryptoconverter.sql
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, 👤 회원관리

#256 fix: null처리 기능 추가
  backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/AbstractCryptoConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/ConverterException.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoDoubleConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/config/converter/CryptoStringConverter.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 👿 버그, 😎 BE
