Repository woowacourse-teams/2021-see-you-there, pull requests merged in 2021-08, with the labels that each got.

#119 [6] 참석자 목록 추가 및 중간 지점 찾기 테스트 코드 추가 v2.3.4
  frontend/.gitignore
  frontend/cypress/fixtures/addressSearchDaechi.json
  frontend/cypress/fixtures/addressSearchJamsil.json
  frontend/cypress/fixtures/midpoint.json
  frontend/cypress/fixtures/midpointCafe.json
  frontend/cypress/fixtures/midpointDining.json
  frontend/cypress/fixtures/midpointParty.json
  frontend/cypress/fixtures/midpointStation.json
  frontend/cypress/integration/midpoint.spec.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/icons/id.js
  frontend/src/components/icons/index.js
  frontend/src/components/molecules/AddressSearchModal/index.js
  frontend/src/components/molecules/NavBar/index.js
  frontend/src/components/molecules/ParticipantList/index.js
  frontend/src/constants/index.js
  frontend/src/constants/kakaoMap.js
  frontend/src/constants/test.js
  frontend/src/contexts/ProfileFormContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/hooks/useMapViewApi.js
  frontend/src/hooks/useMidpoint.js
  frontend/src/hooks/useMutateAddress.js
  frontend/src/hooks/useMutateProfile.js
  frontend/src/hooks/useProfileNicknameInput.js
  frontend/src/pages/Home/ParticipantAddForm.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Profile/ProfileEditForm.js
  frontend/src/pages/Profile/style.js
Labels: 😆 FE, 🧪 테스트

#122 hotfix: 내 프로필 페이지에서 수정사항이 바로 반영되지 않는 문제 해결 v2.3.5
  frontend/src/contexts/UserContext.js
Labels: 👿 버그, 😆 FE

#123 hotfix: profile 수정사항 로컬 상태로 관리하도록 수정 v2.3.6
  frontend/src/contexts/UserContext.js
  frontend/src/hooks/useMutateProfile.js
Labels: 👿 버그, 😆 FE

#127 [hotfix] 로그아웃 상태가 Navbar에 반영되지 않는 문제 해결 v2.3.7
  frontend/package.json
  frontend/src/App.js
  frontend/src/constants/api.js
  frontend/src/contexts/UserContext.js
Labels: 👿 버그, 😆 FE

#136 fix: 친구 조회시 순서 보장하도록 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/FriendShip.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 👤 친구관리, 👿 버그, 😎 BE

#130 [3] 스프린트2 리팩토링 v2.3.8
  .gitignore
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/atoms/Icon/index.js
  frontend/src/components/icons/arrowLeft.js
  frontend/src/components/icons/check.js
  frontend/src/components/icons/checkCircle.js
  frontend/src/components/icons/close.js
  frontend/src/components/icons/copy.js
  frontend/src/components/icons/dropdown.js
  frontend/src/components/icons/enter.js
  frontend/src/components/icons/errorCircle.js
  frontend/src/components/icons/hamburger.js
  frontend/src/components/icons/id.js
  frontend/src/components/icons/index.js
  frontend/src/components/icons/localBar.js
  frontend/src/components/icons/localCafe.js
  frontend/src/components/icons/localDining.js
  frontend/src/components/icons/localParty.js
  frontend/src/components/icons/map.js
  frontend/src/components/icons/paste.js
  frontend/src/components/icons/people.js
  frontend/src/components/icons/person.js
  frontend/src/components/icons/personCircle.js
  frontend/src/components/icons/place.js
  frontend/src/components/icons/removeCircle.js
  frontend/src/components/icons/search.js
  frontend/src/components/icons/star.js
  frontend/src/components/icons/submitRight.js
  frontend/src/components/index.js
  frontend/src/components/molecules/AuthRoute/index.js
  frontend/src/constants/api.js
  frontend/src/contexts/MapViewContext.js
  frontend/src/globalStyle.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Address/index.js
  frontend/src/pages/Friend/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Logout/index.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/NotFound/index.js
  frontend/src/pages/OAuth/index.js
  frontend/src/pages/Profile/index.js
  frontend/src/pages/Welcome/index.js
  frontend/src/pages/index.js
  frontend/webpack.config.js
Labels: ⚒ 리팩토링, 😆 FE

#149 [hotfix] 모바일에서 상단 컨트롤러가 보이지 않는 문제 해결
  frontend/package.json
  frontend/src/components/atoms/Icon/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/constants/api.js
  frontend/src/globalStyle.js
  frontend/src/pages/Address/style.js
  frontend/src/pages/Friend/style.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Login/style.js
  frontend/src/pages/Logout/style.js
  frontend/src/pages/Midpoint/style.js
  frontend/src/pages/NotFound/style.js
  frontend/src/pages/Profile/style.js
  frontend/src/pages/Welcome/style.js
Labels: 👿 버그, 😆 FE

#150 [5] cloudwatch 및 spring actuator metric 설정
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java
  backend/goodday/src/main/resources/application-test.yml
  backend/goodday/src/main/resources/application.yml
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE, 🛠 인프라

#152 fix: develop 과 main 별로 url 다르게 설정
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/resources/application-prod.yml
  backend/goodday/src/main/resources/application-test.yml
Labels: ⚒ 리팩토링, 😎 BE

#153 Feature/cash
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/config/redis/RedisConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrades.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Point.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/request/LocationsRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/location/repository/PathResultRedisRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
Labels: 우선순위 ⭐️⭐️⭐️, 📍 중간지점출력, 😎 BE

#161 [2] refactor: secret 정보를 yml로 이동
  backend/goodday/.gitignore
  backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
  backend/goodday/src/main/resources/application-local.yml
  backend/goodday/src/main/resources/application-prod.yml
  backend/goodday/src/main/resources/application-test.yml
  backend/goodday/src/main/resources/application.yml
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#165 [7] 알고리즘 개선 및 경로개선
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/controller/PathController.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/Paths.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/PointWithName.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/algorithm/Distance.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
  backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
  backend/goodday/src/test/java/seeuthere/goodday/path/PathAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/path/domain/PathTest.java
  backend/goodday/src/test/java/seeuthere/goodday/path/domain/algorithm/DistanceTest.java
Labels: 😎 BE, 📍 교통경로, 우선순위 ⭐️⭐️⭐️

#166 [6] 친구 요청 및 수락
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/RequestFriendRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/RequestFriend.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, 👤 친구관리

#167 [17.5] 중간지점까지의 경로 표시 마크업 및 기능 구현 v3.1.0
  frontend/package.json
  frontend/src/assets/images/pinParticipant.png
  frontend/src/components/atoms/Animation/index.js
  frontend/src/components/atoms/Icon/index.js
  frontend/src/components/molecules/AddressSearchModal/style.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/components/molecules/ParticipantList/style.js
  frontend/src/constants/api.js
  frontend/src/constants/index.js
  frontend/src/constants/kakaoMap.js
  frontend/src/constants/mock.js
  frontend/src/constants/style.js
  frontend/src/contexts/ParticipantContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/globalStyle.js
  frontend/src/hooks/useMapViewApi.js
  frontend/src/hooks/useMidpoint.js
  frontend/src/pages/Address/style.js
  frontend/src/pages/Friend/style.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Login/style.js
  frontend/src/pages/Logout/style.js
  frontend/src/pages/Midpoint/CategoryChips.js
  frontend/src/pages/Midpoint/ParticipantChips.js
  frontend/src/pages/Midpoint/PersonalPath.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
  frontend/src/pages/NotFound/index.js
  frontend/src/pages/NotFound/style.js
  frontend/src/pages/Profile/style.js
  frontend/src/pages/Welcome/style.js
  frontend/src/utils/id.js
Labels: 😆 FE, 📍 교통경로, 우선순위 ⭐️⭐️⭐️

#169 [1] aws cloud watch 충돌 수정
  backend/goodday/.gitignore
  backend/goodday/build.gradle
  backend/goodday/src/docs/asciidoc/list.adoc
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/docs/controller/DocsController.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
Labels: 👿 버그, 😎 BE

#170 [1] 친구 요청 및 요청 받은 목록 조회 api 주소 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
Labels: 😎 BE, ⚒ 리팩토링

#171 [0.5] fix: 개발문서 위치 추가 및 경로 수정
  backend/goodday/src/docs/asciidoc/list.adoc
  backend/goodday/src/docs/asciidoc/member.adoc
Labels: 👿 버그, 😎 BE, 우선순위 ⭐️

#173 [8] 친구 요청 관련 디자인, 마크업 및 기능 구현 v3.2.0
  frontend/package.json
  frontend/src/components/atoms/Icon/index.js
  frontend/src/components/atoms/Notice/index.js
  frontend/src/components/atoms/Notice/style.js
  frontend/src/components/molecules/NavBar/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/constants/api.js
  frontend/src/constants/domain.js
  frontend/src/constants/kakaoMap.js
  frontend/src/constants/route.js
  frontend/src/constants/style.js
  frontend/src/contexts/ProfileFormContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/globalStyle.js
  frontend/src/hooks/useMutateFriend.js
  frontend/src/hooks/useMutateProfile.js
  frontend/src/pages/Friend/FriendSearchModal.js
  frontend/src/pages/Friend/ListReceiveFriend.js
  frontend/src/pages/Friend/ListRequestFriend.js
  frontend/src/pages/Friend/ListUserFriend.js
  frontend/src/pages/Friend/index.js
  frontend/src/pages/Friend/style.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
  frontend/src/pages/Profile/ProfileEditForm.js
  frontend/src/utils/id.js
Labels: 😆 FE, 우선순위 ⭐️⭐️, 👤 친구관리, 👤 회원관리

#177 [3] Sonarqube 적용
  backend/goodday/Jenkinsfile.groovy
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 😎 BE, 🛠 인프라

#179 fix: sonarqube 제거
  backend/goodday/Jenkinsfile.groovy
  backend/goodday/build.gradle
Labels: 😎 BE, 우선순위 ⭐️, ⚒ 리팩토링

#178 [5] 가중치 적용 1차
  backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/WeightStations.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/resources/data/weightedStations.txt
Labels: 😎 BE, 📍 중간지점출력

#180 [fix] 파일경로 수정
  backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java
Labels: 👿 버그, 😎 BE, 우선순위 ⭐️⭐️⭐️

#181 [17] 스낵바 UI, 로딩 UI 마크업 및 기능 구현 v3.3.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/images/avatar1.png
  frontend/src/assets/images/avatar10.png
  frontend/src/assets/images/avatar2.png
  frontend/src/assets/images/avatar3.png
  frontend/src/assets/images/avatar4.png
  frontend/src/assets/images/avatar5.png
  frontend/src/assets/images/avatar6.png
  frontend/src/assets/images/avatar7.png
  frontend/src/assets/images/avatar8.png
  frontend/src/assets/images/avatar9.png
  frontend/src/assets/images/index.js
  frontend/src/assets/images/logoSquare.png
  frontend/src/components/atoms/ProgressBar/index.js
  frontend/src/components/atoms/ProgressBar/style.js
  frontend/src/components/atoms/Spinner/index.js
  frontend/src/components/atoms/Spinner/style.js
  frontend/src/components/index.js
  frontend/src/components/molecules/AddressSearchModal/ListContent.js
  frontend/src/components/molecules/AddressSearchModal/index.js
  frontend/src/components/molecules/AddressSearchModal/style.js
  frontend/src/components/molecules/AuthRoute/index.js
  frontend/src/components/molecules/MidpointLoader/index.js
  frontend/src/components/molecules/MidpointLoader/style.js
  frontend/src/constants/domain.js
  frontend/src/constants/index.js
  frontend/src/constants/style.js
  frontend/src/contexts/AddFormContext.js
  frontend/src/contexts/ParticipantContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/globalStyle.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useCustomSnackbar.js
  frontend/src/hooks/useFriendSearch.js
  frontend/src/hooks/useMutateAddress.js
  frontend/src/hooks/useMutateFriend.js
  frontend/src/hooks/useMutateProfile.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Address/UserAddressForm.js
  frontend/src/pages/Friend/FriendSearchModal.js
  frontend/src/pages/Friend/style.js
  frontend/src/pages/Home/ParticipantAddForm.js
  frontend/src/pages/Home/QuickAddModal.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Profile/ProfileEditForm.js
  frontend/src/pages/Welcome/UserAddressAddForm.js
  frontend/src/pages/Welcome/style.js
  frontend/src/utils/dom.js
  frontend/src/utils/id.js
  frontend/src/utils/index.js
Labels: 😆 FE, 우선순위 ⭐️⭐️⭐️

#183 [1] aws error 안보이도록 수정
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java
Labels: 😎 BE, ⚒ 리팩토링

#184 [9] 캐싱 변경 작업 및 중복된 역 제거 및 가중치 변경
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicateStationRemover.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicatedEdgeCase.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrade.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/TimeGrade.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/UtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/algorithm/Station.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIItemListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIPathListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APITransportResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathsResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/repository/SubwayRedisRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/TransportCache.java
  backend/goodday/src/main/resources/data/weightedStations.txt
Labels: 😎 BE, 📍 중간지점출력, 📍 교통경로, 우선순위 ⭐️⭐️⭐️

#185 [1] 로그 전략 수정
  backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java
Labels: 😎 BE, ⚒ 리팩토링

#189 [4] 멤버 및 친구 기능 예외 처리 구현
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/AuthorizationExtractor.java
  backend/goodday/src/main/java/seeuthere/goodday/group/controller/GroupController.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/Group.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/FriendShip.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/RequestFriend.java
  backend/goodday/src/main/java/seeuthere/goodday/member/exception/MemberExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 👿 버그, 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링, 👤 친구관리, 👤 회원관리

#190 [10] 탐색역 확장, 주요 역 추가, 시간 평균 가중치 조정
  backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrade.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/WeightStations.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/Meta.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/UtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/exception/LocationExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java
  backend/goodday/src/main/resources/data/weightedStations.txt
Labels: 😎 BE, 📍 중간지점출력, 📍 교통경로, 우선순위 ⭐️⭐️⭐️

#191 [1] 친구 검색 관련 예외 오류 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/exception/MemberExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
Labels: 👿 버그, 😎 BE

#192 [4] 프론트엔드 스프린트3 종합 버그픽스 v3.4.1
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/atoms/ProgressBar/index.js
  frontend/src/components/atoms/ProgressBar/style.js
  frontend/src/components/molecules/MidpointLoader/index.js
  frontend/src/constants/style.js
  frontend/src/contexts/MapViewContext.js
  frontend/src/contexts/ParticipantContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/hooks/useFriendSearch.js
  frontend/src/hooks/useMapViewApi.js
  frontend/src/hooks/useMutateFriend.js
  frontend/src/hooks/useMutateProfile.js
  frontend/src/pages/Friend/FriendSearchModal.js
  frontend/src/pages/Midpoint/ParticipantChips.js
  frontend/src/pages/Midpoint/PersonalPath.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
Labels: 👿 버그, 😆 FE

#194 [8] 멀티 스레드 환경에서의 WebClient 크롤링 개선
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/PathTransferResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
Labels: 😎 BE, 📍 중간지점출력, 📍 장소카테고리, 📍 교통경로, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#196 [4] 프론트엔드 테스트 자동화 적용
  .github/workflows/fe-tests.yml
  frontend/cypress/integration/midpoint.spec.js
  frontend/cypress/support/commands.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/contexts/MapViewContext.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
Labels: 😆 FE, 우선순위 ⭐️⭐️⭐️, 🧪 테스트

#197 [1] Requesters refactor
  backend/goodday/src/main/java/seeuthere/goodday/location/config/LocationRequestConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/config/Requesters.java
  backend/goodday/src/main/java/seeuthere/goodday/location/config/WeightStationConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/WeightStations.java
  backend/goodday/src/main/java/seeuthere/goodday/location/exception/LocationExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/TransportCache.java
  backend/goodday/src/main/java/seeuthere/goodday/path/repository/SubwayRedisRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
Labels: 😎 BE, 우선순위 ⭐️, ⚒ 리팩토링

#199 docs: 리드미 업데이트
  .github/workflows/fe-tests.yml
  README.md
  backend/README.md
  frontend/README.md
Labels: 😆 FE

#200 [1] 유료도메인 연결허용
  backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, 🛠 인프라

#201 [1] 프론트엔드 유료도메인 연결
  README.md
  frontend/src/constants/api.js
Labels: 😆 FE

#203 main develop 충돌 해결
  backend/README.md
  frontend/README.md
Labels: ⚒ 리팩토링

#204 도메인 변경 반영
  .github/workflows/fe-tests.yml
  README.md
  backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
  frontend/src/constants/api.js
Labels: 😆 FE, 😎 BE

#206 [2] WebClient 사용방법 수정
  backend/goodday/src/main/java/seeuthere/goodday/auth/exception/AuthExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/NaverUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/CoordinateRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/LocationRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/SearchRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/exception/LocationExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/requester/TransportRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/path/exception/PathExceptionSet.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#208 [10] 로그인, 설정 리팩터링
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java
  backend/goodday/src/main/java/seeuthere/goodday/GoodDayApplication.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/AuthRequestConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/KakaoAuthRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/NaverAuthRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/EnableAuthArgumentResolver.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/AccessTokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/KakaoAccount.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/KakaoProfile.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/KakaoResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileTokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/TokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/exception/AuthExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/AuthorizationExtractor.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/JwtTokenProvider.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/MemberInterceptor.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/KaKaoService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/KakaoService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/NaverService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/config/redis/RedisConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/config/Requesters.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/FriendShip.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/RequestFriend.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
  backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
Labels: 😎 BE, ⚒ 리팩토링
