Repository woowacourse-teams/2021-see-you-there, pull requests merged in 2021-09, with the labels that each got.

#211 [6] flyway 적용
  backend/goodday/.gitignore
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java
  backend/goodday/src/main/resources/db/migration/V1__init.sql
Labels: 😎 BE, 우선순위 ⭐️⭐️

#219 [1]bugfix 경로 정보 찾기 버그 수정
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
Labels: 👿 버그, 😎 BE

#223 [20] 테스트 추가, 테스트 효율성 개선, QnA게시판 추가, gzip 적용
  backend/goodday/build.gradle
  backend/goodday/src/docs/asciidoc/board.adoc
  backend/goodday/src/docs/asciidoc/list.adoc
  backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dao/BoardRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dao/CommentRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/Board.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/BoardLabel.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/Comment.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/BoardRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/BoardResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/CommentRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/CommentResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/board/exception/BoardExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/AdminRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Admin.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/exception/MemberExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/main/resources/db/migration/V1__init.sql
  backend/goodday/src/main/resources/db/migration/V2__qnatable.sql
  backend/goodday/src/test/java/seeuthere/goodday/AcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/TestMethod.java
  backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/board/domain/BoardTest.java
  backend/goodday/src/test/java/seeuthere/goodday/location/LocationAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/path/PathAcceptanceTest.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링, 🧪 테스트

#224 [1] 코드 스멜 제거
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/AuthRequestConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/NaverAuthRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/exception/AuthExceptionSet.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/NaverService.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Location.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIAxisDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIAxisResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APILocationDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APILocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/Meta.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#225 [0.5] 코드 스멜 처리 및 포맷팅
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/AuthRequestConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/config/KakaoAuthRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/AuthorizationExtractor.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/JwtTokenProvider.java
  backend/goodday/src/main/java/seeuthere/goodday/board/domain/BoardLabel.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/BoardResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/CommentRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/request/CommentResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicateStationRemover.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicatedEdgeCase.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/StationGrades.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Points.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/AdminRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/FriendRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/FriendResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/RequestFriendResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/config/PathRequestConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/Route.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/TransportCache.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/algorithm/Stations.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/requester/TransportRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIItemListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIPathListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APITransportResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/RouteResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/secret/SecretKey.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#226 [0.5] fix: 포맷팅 후 충돌 해결
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/PathResult.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/TransportCache.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIItemListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APITransportResponse.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#228 [0.2] refactor: major minor level code smell 일부 제거
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/board/controller/BoardController.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/BoardResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/board/dto/response/CommentResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/algorithm/DuplicateStationRemover.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/combiner/AxisKeywordCombiner.java
  backend/goodday/src/test/java/seeuthere/goodday/board/BoardAcceptanceTest.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, ⚒ 리팩토링

#232 fix: 주소 생성 문제 해결
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/Path.java
Labels: 👿 버그, 😎 BE, ⚒ 리팩토링

#234 fix: address 생성문제 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
Labels: 👿 버그, 😎 BE, ⚒ 리팩토링

#236 hotfix: api/docs 버그 관련 build.gradle 추가
  backend/goodday/build.gradle
Labels: 👿 버그, 😎 BE

#243 배포서버 DB 레플리케이션 적용
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/GoodDayApplication.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java
  backend/goodday/src/main/java/seeuthere/goodday/board/service/BoardService.java
  backend/goodday/src/main/java/seeuthere/goodday/config/replication/DataSourceConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/config/replication/RoutingDataSource.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
Labels: 😎 BE, 우선순위 ⭐️⭐️⭐️, 🛠 인프라

#246 [0.5] build.gradle 수정
  backend/goodday/build.gradle
Labels: 😎 BE, 우선순위 ⭐️
