Repository woowacourse-teams/2021-see-you-there, pull requests merged in 2021-07, with the labels that each got.

#16 [3.5] 프론트엔드 개발 환경설정
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/index.js
  frontend/src/constants/index.js
  frontend/src/hooks/index.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/index.js
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️⭐️, 😆 FE

#13 [3] 백엔드 환경설정
  .gitignore
  backend/goodday/.gitignore
  backend/goodday/README.md
  backend/goodday/build.gradle
  backend/goodday/gradle/wrapper/gradle-wrapper.jar
  backend/goodday/gradle/wrapper/gradle-wrapper.properties
  backend/goodday/gradlew
  backend/goodday/gradlew.bat
  backend/goodday/settings.gradle
  backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java
  backend/goodday/src/main/resources/application-local.yml
  backend/goodday/src/main/resources/application-prod.yml
  backend/goodday/src/main/resources/application-test.yml
  backend/goodday/src/main/resources/application.yml
  backend/goodday/src/test/java/seeuthere/goodday/GooddayApplicationTests.java
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE

#18 [3] 도메인 설계
  backend/goodday/src/main/java/seeuthere/goodday/GooddayApplication.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/Group.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/Location.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Guest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE

#21 [6.5] 내비게이션 바 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/icons/arrowLeft.js
  frontend/src/components/icons/check.js
  frontend/src/components/icons/checkCircle.js
  frontend/src/components/icons/enter.js
  frontend/src/components/icons/errorCircle.js
  frontend/src/components/icons/expandLeft.js
  frontend/src/components/icons/hamburger.js
  frontend/src/components/icons/localBar.js
  frontend/src/components/icons/localCafe.js
  frontend/src/components/icons/localDining.js
  frontend/src/components/icons/people.js
  frontend/src/components/icons/person.js
  frontend/src/components/icons/personCircle.js
  frontend/src/components/icons/place.js
  frontend/src/components/icons/removeCircle.js
  frontend/src/components/icons/search.js
  frontend/src/components/icons/submitRight.js
  frontend/src/components/index.js
  frontend/src/components/molecules/NavBar/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/constants/index.js
  frontend/src/constants/route.js
  frontend/src/constants/style.js
  frontend/src/globalStyle.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️⭐️, 📍 라우팅, 😆 FE

#30 [1] Mock API 생성
  backend/goodday/.gitignore
  backend/goodday/README.md
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/group/controller/GroupController.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/Group.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java
  backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Guest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/main/resources/application-local.yml
  backend/goodday/src/main/resources/application.yml
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE

#29 [8] 카카오 소셜 로그인/로그아웃
  backend/goodday/.gitignore
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Kakao.java
Labels: 우선순위 ⭐️⭐️⭐️, 👤 로그인, 😎 BE

#31 hotfix: redirect_uri 수정 및 webflux 의존성 추가
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Kakao.java
Labels: 😎 BE

#34 fix: 대소문자 에러 수정
  frontend/src/pages/index.js
Labels: 👿 버그, 😆 FE

#39 [7] 네이버 소셜로그인
  backend/goodday/build.gradle
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Kakao.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Naver.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileDto.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/TokenDto.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/Group.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
Labels: 우선순위 ⭐️⭐️, 👤 로그인, 😎 BE

#44 [4] 로그인시 회원 정보 저장
  backend/goodday/src/main/java/seeuthere/goodday/ControllerAdvice.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Kakao.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/Naver.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfiguration.java
  backend/goodday/src/main/java/seeuthere/goodday/exception/CustomException.java
  backend/goodday/src/main/java/seeuthere/goodday/exception/ErrorResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java
  backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/CoordinateRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/LocationRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/Document.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/LocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/Meta.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/main/resources/application-local.yml
  backend/goodday/src/main/resources/application-prod.yml
  backend/goodday/src/main/resources/application-test.yml
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 우선순위 ⭐️⭐️, 👤 로그인, 😎 BE

#48 [2] 도메인 및 DTO 관련 리팩토링
  backend/goodday/src/main/java/seeuthere/goodday/group/domain/History.java
  backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/AxisKeywordCombiner.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/combiner/AxisKeywordCombiner.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Location.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/MiddlePoint.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Point.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/CoordinateRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/LocationRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/SearchRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/requester/UtilityRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/AxisResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/LocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/Meta.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/Response.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/UtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIAxisDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIAxisResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APILocationDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APILocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/component/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/request/LocationRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/request/LocationsRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/LocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/MiddlePointResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/ResponseFormat.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/SpecificLocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/UtilityResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
Labels: ⚒ 리팩토링, 우선순위 ⭐️, 😎 BE

#50 [1] 백엔드 CORS 문제 해결
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE

#51 [13.5] HomePage 기능, MidpointPage 기능 및 마크업
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/images/avatar.png
  frontend/src/assets/images/avatar1.png
  frontend/src/assets/images/avatar10.png
  frontend/src/assets/images/avatar2.png
  frontend/src/assets/images/avatar3.png
  frontend/src/assets/images/avatar4.png
  frontend/src/assets/images/avatar5.png
  frontend/src/assets/images/avatar6.png
  frontend/src/assets/images/avatar7.png
  frontend/src/assets/images/avatar8.png
  frontend/src/assets/images/avatar9.png
  frontend/src/assets/images/index.js
  frontend/src/components/atoms/ButtonRound/style.js
  frontend/src/components/atoms/InputWithButton/index.js
  frontend/src/components/atoms/InputWithButton/style.js
  frontend/src/components/atoms/Modal/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/components/molecules/ParticipantList/index.js
  frontend/src/components/molecules/ParticipantList/style.js
  frontend/src/constants/api.js
  frontend/src/constants/domain.js
  frontend/src/constants/index.js
  frontend/src/constants/mock.js
  frontend/src/constants/style.js
  frontend/src/globalStyle.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useConfirm.js
  frontend/src/hooks/useMapView.js
  frontend/src/hooks/useModal.js
  frontend/src/hooks/useParticipantForm.js
  frontend/src/hooks/useParticipantRemoveConfirm.js
  frontend/src/hooks/useParticipants.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
  frontend/src/pages/index.js
  frontend/src/utils/httpRequest.js
  frontend/src/utils/id.js
  frontend/src/utils/index.js
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️⭐️, 📍 주소입력, 📍 중간지점출력, 😆 FE

#52 fix: 배포 시 react-refresh 실행되는 문제 해결
  frontend/package.json
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️⭐️, 👿 버그, 😆 FE

#55 [9] 로그인 / 로그아웃 마크업 및 기능 구현
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/images/drawingLogin.png
  frontend/src/assets/images/index.js
  frontend/src/assets/images/logoKakao.png
  frontend/src/assets/images/logoNaver.png
  frontend/src/assets/index.js
  frontend/src/assets/lotties/logout.json
  frontend/src/components/atoms/Animation/index.js
  frontend/src/components/atoms/Input/style.js
  frontend/src/components/index.js
  frontend/src/components/molecules/NavBar/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/constants/api.js
  frontend/src/constants/index.js
  frontend/src/constants/route.js
  frontend/src/constants/style.js
  frontend/src/globalStyle.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Login/style.js
  frontend/src/pages/Logout/index.js
  frontend/src/pages/Logout/style.js
  frontend/src/pages/OAuth/index.js
  frontend/src/pages/index.js
  frontend/src/utils/index.js
  frontend/src/utils/localStorage.js
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️, 👤 로그인, 😆 FE

#61 feat: rest docs 초기 설정 추가
  backend/goodday/.gitignore
  backend/goodday/build.gradle
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
  backend/goodday/src/test/java/seeuthere/goodday/study/AcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/study/MapTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE

#70 [10.5] 스프린트1 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/index.js
  frontend/src/assets/lotties/logoutAnimation.json
  frontend/src/components/atoms/Animation/index.js
  frontend/src/components/atoms/Input/index.js
  frontend/src/components/atoms/InputWithButton/index.js
  frontend/src/components/icons/checkCircle.js
  frontend/src/components/icons/close.js
  frontend/src/components/molecules/Confirm/index.js
  frontend/src/components/molecules/Confirm/style.js
  frontend/src/components/molecules/NavBar/index.js
  frontend/src/components/molecules/ParticipantList/index.js
  frontend/src/contexts/ParticipantAddFormContext.js
  frontend/src/contexts/ParticipantContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/contexts/index.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useConfirm.js
  frontend/src/hooks/useMapView.js
  frontend/src/hooks/useMidpoint.js
  frontend/src/hooks/useParticipantAddressInput.js
  frontend/src/hooks/useParticipantAddressSearch.js
  frontend/src/hooks/useParticipantForm.js
  frontend/src/hooks/useParticipantNameInput.js
  frontend/src/hooks/useParticipantRemoveConfirm.js
  frontend/src/hooks/useParticipants.js
  frontend/src/pages/Home/ParticipantAddForm.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Login/index.js
  frontend/src/pages/Logout/index.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/OAuth/index.js
  frontend/src/utils/index.js
  frontend/src/utils/localStorage.js
  frontend/src/utils/storage.js
  frontend/webpack.config.js
Labels: ⚒ 리팩토링, 우선순위 ⭐️, 😆 FE

#67 [3.5] Location 기능 Test 코드에 Restdocs 적용
  backend/goodday/src/docs/asciidoc/axis.adoc
  backend/goodday/src/docs/asciidoc/coordinate.adoc
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/docs/asciidoc/keyword.adoc
  backend/goodday/src/docs/asciidoc/midPoint.adoc
  backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/infrastructure/MemberInterceptor.java
  backend/goodday/src/main/java/seeuthere/goodday/docs/controller/DocsController.java
  backend/goodday/src/main/java/seeuthere/goodday/exception/ErrorResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/MiddlePointResponse.java
  backend/goodday/src/main/resources/static/favicon.ico
  backend/goodday/src/test/java/seeuthere/goodday/AcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/location/LocationAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/location/LocationsDto.java
  backend/goodday/src/test/java/seeuthere/goodday/study/MapTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 😎 BE, 🧪 테스트

#91 [4] feat: rest docs 목록 생성
  backend/goodday/src/docs/asciidoc/index.adoc
Labels: 우선순위 ⭐️⭐️, 😎 BE, 🧪 테스트

#92 [7] 새로고침 후 로그인 유지 및 회원 정보 수정
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/EnableAuthArgumentResolver.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/domain/EnableAuth.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/TokenDto.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/KaKaoService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/NaverService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/NaverUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 👤 로그인, 👤 회원관리, 😎 BE

#93 [1] 회원 관리 테스트 및 리팩토링
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/combiner/AxisKeywordCombiner.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/AcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/location/LocationAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
  backend/goodday/src/test/java/seeuthere/goodday/study/MapTest.java
Labels: ⚒ 리팩토링, 우선순위 ⭐️⭐️⭐️, 👤 회원관리, 😎 BE, 🧪 테스트

#96 [14] 장소 카테고리 선택 마크업 및 기능 구현
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/icons/index.js
  frontend/src/components/icons/localParty.js
  frontend/src/components/icons/map.js
  frontend/src/constants/domain.js
  frontend/src/constants/index.js
  frontend/src/constants/kakaoMap.js
  frontend/src/constants/style.js
  frontend/src/contexts/MapViewContext.js
  frontend/src/contexts/ParticipantContext.js
  frontend/src/contexts/UserContext.js
  frontend/src/contexts/index.js
  frontend/src/globalStyle.js
  frontend/src/hooks/index.js
  frontend/src/hooks/useMapView.js
  frontend/src/hooks/useMapViewApi.js
  frontend/src/hooks/useMidpoint.js
  frontend/src/index.html
  frontend/src/pages/Home/ParticipantAddForm.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Home/style.js
  frontend/src/pages/Midpoint/index.js
  frontend/src/pages/Midpoint/style.js
  frontend/src/utils/id.js
  frontend/src/utils/storage.js
  frontend/webpack.config.js
Labels: 우선순위 ⭐️⭐️⭐️, 📍 장소카테고리, 😆 FE

#102 [7] 회원 주소 관리
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileTokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/TokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/KaKaoService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/NaverService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/NaverUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/AddressRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Guest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Person.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressDeleteRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressUpdateRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/main/resources/application-test.yml
  backend/goodday/src/main/resources/application.yml
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 👤 회원관리, 📍 주소입력, 😎 BE

#101 [1] 장소 URL 에 대한 정보 추가
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/combiner/AxisKeywordCombiner.java
  backend/goodday/src/main/java/seeuthere/goodday/location/domain/location/Location.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/api/response/APIUtilityDocument.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/LocationResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/UtilityResponse.java
Labels: 우선순위 ⭐️⭐️, 📍 장소카테고리, 📍 중간지점출력, 😎 BE

#103 [7] 교통수단 API에서 정보 가져오기 및 가공
  backend/goodday/build.gradle
  backend/goodday/src/docs/asciidoc/axis.adoc
  backend/goodday/src/docs/asciidoc/coordinate.adoc
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/docs/asciidoc/keyword.adoc
  backend/goodday/src/docs/asciidoc/location.adoc
  backend/goodday/src/docs/asciidoc/midPoint.adoc
  backend/goodday/src/docs/asciidoc/path.adoc
  backend/goodday/src/main/java/seeuthere/goodday/auth/AuthenticationPrincipalConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebClientConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/location/service/LocationService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/controller/PathController.java
  backend/goodday/src/main/java/seeuthere/goodday/path/domain/requester/TransportRequester.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIItemListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIMsgBodyResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APIPathListResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/api/response/APITransportResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/PathsResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/dto/response/RouteResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/path/service/PathService.java
  backend/goodday/src/main/java/seeuthere/goodday/path/util/TransportURL.java
  backend/goodday/src/test/java/seeuthere/goodday/path/PathAcceptanceTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 📍 교통경로, 😎 BE

#104 [1] REST API에 맞는 URL 수정 및 Response 리팩토링
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/docs/asciidoc/locations.adoc
  backend/goodday/src/docs/asciidoc/paths.adoc
  backend/goodday/src/main/java/seeuthere/goodday/location/controller/LocationController.java
  backend/goodday/src/main/java/seeuthere/goodday/location/dto/response/ResponseFormat.java
  backend/goodday/src/test/java/seeuthere/goodday/location/LocationAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/study/MapTest.java
Labels: ⚒ 리팩토링, 우선순위 ⭐️, 😆 FE, 😎 BE

#106 [14] 친구 관리 기능
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/AddressRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/FriendShip.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressUpdateRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/FriendRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/FriendResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/main/resources/application.yml
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: 우선순위 ⭐️⭐️⭐️, 👤 친구관리, 😎 BE

#108 [hotfix]주소 요청, 응답 필드 수정
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Address.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/AddressUpdateRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: ⚒ 리팩토링, 👤 회원관리, 📍 주소입력, 😎 BE

#110 [3] 친구 검색
  backend/goodday/src/docs/asciidoc/index.adoc
  backend/goodday/src/docs/asciidoc/member.adoc
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileTokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/KaKaoService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/NaverService.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/KakaoUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/utils/NaverUtil.java
  backend/goodday/src/main/java/seeuthere/goodday/config/WebConfig.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/FriendController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/controller/MemberController.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dao/MemberRepository.java
  backend/goodday/src/main/java/seeuthere/goodday/member/domain/Member.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/FriendResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberRequest.java
  backend/goodday/src/main/java/seeuthere/goodday/member/dto/MemberResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/DataLoader.java
  backend/goodday/src/test/java/seeuthere/goodday/member/controller/MemberAcceptanceTest.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: ⚒ 리팩토링, 우선순위 ⭐️⭐️⭐️, 👤 친구관리, 😎 BE

#114 fix: 로그인이 되지 않는 문제 해결
  frontend/src/pages/OAuth/index.js
Labels: 👿 버그, 😆 FE

#115 fix: 로그인 페이지 및 웰컴 페이지 버그 해결
  frontend/src/components/molecules/AuthRoute/index.js
  frontend/src/contexts/UserContext.js
  frontend/src/pages/Home/ParticipantAddForm.js
  frontend/src/pages/Home/QuickAddModal.js
  frontend/src/pages/OAuth/index.js
  frontend/src/pages/Welcome/UserAddressAddForm.js
Labels: 우선순위 ⭐️⭐️⭐️, 👿 버그, 😆 FE

#117 [hotfix] 기존 회원로그인시 회원 memberId 반환하도록 수정
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/KakaoController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/controller/NaverController.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/dto/ProfileTokenResponse.java
  backend/goodday/src/main/java/seeuthere/goodday/auth/service/AuthService.java
  backend/goodday/src/main/java/seeuthere/goodday/member/service/MemberService.java
  backend/goodday/src/test/java/seeuthere/goodday/member/domain/MemberTest.java
Labels: ⚒ 리팩토링, 👿 버그, 😎 BE

#118 [hotfix] AuthRoute 카카오 로그인 문제 해결
  frontend/src/components/molecules/AuthRoute/index.js
  frontend/src/components/molecules/NavBar/style.js
  frontend/src/contexts/UserContext.js
  frontend/src/pages/NotFound/index.js
Labels: 👿 버그, 😆 FE
